### ISSUE TITLE
Scan through chapter 3

### ISSUE THREAD

**Issue by fnattino** [escience-academy/lesson-parallel-python#8]

**Comment by svenvanderburg** [comment]
* Fix weird code block of first challenge, add outcome of timing.
* Remove timing of naive `calc_pi` function (because we already did it in the challenge)
* Rename `numba_sum_range` to `sum_range_numba` to make it consistent across episode
* Numbify comp_pi challenge: just write out the solution so that it is explicit.
* Make discussion on vectorization more explicit so that every teacher would be able to lead the discussion (i.e. what are drawbacks of numpy vectorization)
* Make questions and objectives clearer.

To discuss:
* Drop the part on multithreading, it makes the episode incoherent, and probably only confuses things.
* Also add an example of multiprocessing for `calc_pi` to show that for this particular problem it is not useful? (but at least learners have seen it and can contrast it with numba)

**Comment by svenvanderburg** [comment]
New issues were created to address above points, closing issue.
